import { useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { apiRequest } from "../../services/apiClient.js";
import { getAdvertisingCatalog } from "../../services/contentService.js";
import { usePreferences } from "../../store/PreferencesContext.jsx";
import UiIcon from "../../components/UiIcon.jsx";

const statusLabels={DRAFT:"Bản nháp",PENDING_REVIEW:"Chờ xét duyệt",RESUBMITTED:"Đã gửi lại",NEEDS_REVISION:"Cần chỉnh sửa",APPROVED:"Đã duyệt",REJECTED:"Bị từ chối",ACTIVE:"Đang hiệu lực",PAID:"Đã thanh toán",UNPAID:"Chưa thanh toán",PROPOSED:"Đã có đề xuất",SCHEDULED:"Đã lên lịch",COMPLETED:"Đã hoàn thành",CANCELLED:"Đã hủy",EXPIRED:"Hết hạn"};
const status=value=>statusLabels[value] || value || "Chưa có";
const currency=value=>Number(value || 0).toLocaleString("vi-VN")+" ₫";
const time=value=>value?String(value).replace("T"," ").slice(0,16):"—";
const datetime=value=>value?String(value).replace(" ","T").slice(0,16):"";
const editable=value=>["DRAFT","NEEDS_REVISION"].includes(value);
const empty={company:{},documents:[],contracts:[],campaigns:[]};

function Field({label,children}) {return <label className="business-field"><span>{label}</span>{children}</label>;}
function Badge({value}) {return <span className={`status-pill business-badge badge-${String(value || 'EMPTY').toLowerCase()}`}>{status(value)}</span>;}

export default function BusinessWorkspacePage({screen}) {
  const { tr }=usePreferences();const params=useParams();const navigate=useNavigate();const [query]=useSearchParams();
  const [data,setData]=useState(empty);const [catalog,setCatalog]=useState(null);const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [companyForm,setCompanyForm]=useState({name:"",taxCode:"",email:"",phone:"",address:"",billingAddress:""});
  const [booking,setBooking]=useState({name:"",slotId:query.get("slotId") || "",packageId:query.get("packageId") || "",startDate:query.get("startDate") || "",endDate:query.get("endDate") || ""});
  const [campaignForm,setCampaignForm]=useState({name:"",description:"",contractId:"",startTime:"",endTime:""});
  const [file,setFile]=useState(null);const [targetUrl,setTargetUrl]=useState("");
  const queryString=query.toString();
  useEffect(()=>{if(screen.id==="BUS-07") {const selected=new URLSearchParams(queryString);setBooking({name:"",slotId:selected.get("slotId") || "",packageId:selected.get("packageId") || "",startDate:selected.get("startDate") || "",endDate:selected.get("endDate") || ""});}},[screen.id,queryString]);
  const current=data.campaigns.find(c=>String(c.campaign_id)===params.campaignId);
  const contract=data.contracts.find(c=>String(c.contract_id)===params.contractId);
  async function refresh(){const result=await apiRequest("/api/business/workspace");setData(result);return result;}
  useEffect(()=>{let alive=true;setLoading(true);setError("");setMessage("");setFile(null);
    Promise.all([apiRequest("/api/business/workspace"),getAdvertisingCatalog()]).then(([result,offers])=>{if(!alive)return;
      setData(result);setCatalog(offers);const c=result.company;
      setCompanyForm({name:c.company_name || "",taxCode:c.tax_code || "",email:c.email || "",phone:c.phone || "",address:c.address || "",billingAddress:c.billing_address || ""});
      const selected=result.campaigns.find(row=>String(row.campaign_id)===params.campaignId);
      setCampaignForm(selected?{name:selected.campaign_name,description:selected.description || "",contractId:String(selected.contract_id),startTime:datetime(selected.scheduled_start_time),endTime:datetime(selected.scheduled_end_time)}:{name:"",description:"",contractId:"",startTime:"",endTime:""});
      setTargetUrl(selected?.target_url || "");
    }).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return ()=>{alive=false;};
  },[screen.id,params.campaignId,params.contractId]);
  async function action(task,success,after){if(busy)return;setBusy(true);setError("");setMessage("");try{const result=await task();await refresh();setMessage(success);after?.(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const json=(path,body,method="POST")=>apiRequest(path,{method,body:JSON.stringify(body)});
  const activeContracts=data.contracts.filter(c=>c.status==="ACTIVE" && c.payment_status==="PAID" && new Date(c.end_at)>new Date());
  const isProfile=screen.id==="BUS-02";const isApplication=["BUS-03","BUS-04"].includes(screen.id);
  const isCampaign=["BUS-14","BUS-15","BUS-16","BUS-17"].includes(screen.id);
  return <main className="page-content business-live"><div className="page-heading"><div><p className="eyebrow">THE PULSE BUSINESS · {screen.id}</p><h1>{tr(screen.name)}</h1><p className="page-subtitle">Hồ sơ, hợp đồng và chiến dịch — mọi thông tin trong một không gian.</p></div><button className="secondary-button" disabled={busy || loading} onClick={()=>action(refresh,"Đã cập nhật dữ liệu mới nhất.")}>Làm mới</button></div>
    {error && <p role="alert" className="form-error">{error}</p>}{message && <p role="status" className="success-message">{message}</p>}
    {loading?<p className="loading-card">Đang tải dữ liệu doanh nghiệp…</p>:<>
    {screen.id==="BUS-01" && <>
      <section className="business-welcome"><div><span className="welcome-kicker">THE PULSE · ĐỐI TÁC QUẢNG CÁO</span><h2>Thương hiệu của bạn.<br/><span>Đúng nơi, đúng thời điểm.</span></h2><p>Quản lý hợp tác và chiến dịch trong một không gian. Theo dõi từng bước, từ đặt vị trí đến hiệu quả quảng cáo.</p><Link className="welcome-cta" to="/business/campaigns/edit">Tạo chiến dịch <UiIcon name="arrow"/></Link></div><div className="welcome-emblem" aria-hidden="true"><span>P<span className="emblem-dot">.</span></span><small>MAKE AN IMPACT</small></div></section>
      <section className="stats-grid business-overview-stats">{[["company","Hợp tác doanh nghiệp",status(data.company.application_status),"Trạng thái hồ sơ hiện tại"],["document","Hợp đồng hiệu lực",activeContracts.length,"Đã thanh toán, còn thời hạn"],["campaign","Chiến dịch đã tạo",data.campaigns.length,"Tất cả trạng thái"],["calendar","Chiến dịch chờ duyệt",data.campaigns.filter(c=>c.status==="PENDING_REVIEW").length,"Đang chờ quản lý xử lý"]].map(([icon,label,value,note])=><article className="stat-card" key={label}><div className="stat-topline"><span>{label}</span><UiIcon name={icon}/></div><strong className={typeof value==="string"?"business-status-heading":""}>{value}</strong><small>{note}</small></article>)}</section>
      <div className="business-dashboard-columns"><section className="dashboard-section"><div className="section-heading"><div><p className="section-kicker">CAMPAIGN WORKSPACE</p><h2>Chiến dịch gần đây</h2></div><Link to="/business/campaigns">Xem tất cả ↗</Link></div><div className="recent-campaigns">{data.campaigns.slice(0,3).map(c=><Link className="recent-campaign" key={c.campaign_id} to={`/business/campaigns/${c.campaign_id}`}><div className="recent-campaign-media">{c.media_url?<img src={c.media_url} alt=""/>:<UiIcon name="campaign"/>}</div><div><strong>{c.campaign_name}</strong><small>{c.contract_code} · {time(c.scheduled_start_time)}</small><Badge value={c.status}/></div><UiIcon name="arrow"/></Link>)}</div>{!data.campaigns.length && <p>Chưa có chiến dịch. Tạo chiến dịch đầu tiên khi hợp đồng đã có hiệu lực.</p>}</section>
      <section className="dashboard-section business-shortcuts"><p className="section-kicker">QUICK ACCESS</p><h2>Bạn muốn làm gì?</h2><div className="business-test-steps">{[["company","Hồ sơ & hợp tác","Thông tin công ty, tài liệu pháp lý","/business/company"],["calendar","Đặt vị trí quảng cáo","Bảng giá và lịch quảng cáo","/business/advertising/calendar"],["campaign","Quản lý chiến dịch","Nội dung banner và trạng thái duyệt","/business/campaigns"],["chart","Theo dõi hiệu quả","Lượt hiển thị, click và báo cáo","/business/performance"]].map(([icon,title,detail,path])=><Link to={path} key={path}><span className="shortcut-icon"><UiIcon name={icon}/></span><span><strong>{title}</strong><small>{detail}</small></span><UiIcon name="arrow"/></Link>)}</div></section></div>
      <p className="business-demo-footnote">Tài khoản business.demo có hợp đồng mẫu đã thanh toán. Để thử đăng ký hợp tác từ đầu, tạo tài khoản Doanh nghiệp mới.</p>
    </>}
    {isProfile && <form className="dashboard-section" onSubmit={e=>{e.preventDefault();action(()=>json("/api/business/company",companyForm,"PUT"),"Đã lưu hồ sơ doanh nghiệp vào MySQL.");}}><h2>Thông tin doanh nghiệp</h2><div className="business-form-grid">{[["name","Tên pháp lý",150],["taxCode","Mã số thuế (10 số hoặc 10 số-3 số)",14],["email","Email liên hệ",254],["phone","Số điện thoại",30],["address","Địa chỉ",500],["billingAddress","Địa chỉ xuất hóa đơn",500]].map(([key,label,max])=><Field key={key} label={label}><input value={companyForm[key]} onChange={e=>setCompanyForm({...companyForm,[key]:e.target.value})} type={key==="email"?"email":"text"} maxLength={max} required={key!=="billingAddress"} disabled={busy || ["PENDING_REVIEW","RESUBMITTED"].includes(data.company.application_status) || (data.company.application_status==="APPROVED" && ["name","taxCode"].includes(key))}/></Field>)}</div><div className="form-actions"><button disabled={busy || ["PENDING_REVIEW","RESUBMITTED"].includes(data.company.application_status)}>Lưu hồ sơ</button><Link className="outline-button" to="/business/partnership/apply">Tiếp tục đăng ký hợp tác →</Link></div></form>}
    {isApplication && <section className="dashboard-section"><h2>Hồ sơ hợp tác</h2><Badge value={data.company.application_status}/><dl className="business-details"><dt>Doanh nghiệp</dt><dd>{data.company.company_name || "Chưa có hồ sơ"}</dd><dt>Mã hồ sơ</dt><dd>{data.company.application_code || "—"}</dd><dt>Thời gian gửi</dt><dd>{time(data.company.submitted_at)}</dd><dt>Phản hồi quản lý</dt><dd>{data.company.review_note || "Chưa có phản hồi"}</dd></dl>
      <h3>Tài liệu pháp lý</h3>{data.documents.length?<ul className="business-document-list">{data.documents.map(doc=><li key={doc.document_id}><a href={`/api/media/document/${doc.document_id}`} target="_blank" rel="noreferrer">{doc.original_file_name} ↗</a><small>Phiên bản {doc.version_no} · {time(doc.uploaded_at)}</small></li>)}</ul>:<p>Chưa tải tài liệu.</p>}
      {!data.company.company_id?<Link className="button-link" to="/business/company">Lưu hồ sơ doanh nghiệp trước →</Link>:editable(data.company.application_status)?<><form onSubmit={e=>{e.preventDefault();const body=new FormData();body.append("file",file);action(()=>apiRequest("/api/business/documents",{method:"POST",body}),"Đã tải tài liệu và lưu thông tin vào MySQL.",()=>setFile(null));}}><Field label="PDF, PNG hoặc JPEG · tối đa 8 MB"><input type="file" accept="application/pdf,image/png,image/jpeg" required disabled={busy} onChange={e=>setFile(e.target.files?.[0] || null)}/></Field><button className="secondary-button" disabled={busy || !file}>Tải tài liệu lên</button></form><button disabled={busy || !data.documents.length} onClick={()=>action(()=>apiRequest("/api/business/application/submit",{method:"POST"}),"Đã gửi hồ sơ chờ quản lý xét duyệt.")}>Gửi đăng ký hợp tác</button></>:<p className="info-note">{data.company.application_status==="APPROVED"?"Doanh nghiệp đã được duyệt, có thể đặt quảng cáo.":"Hồ sơ đã khóa. Chờ quản lý xét duyệt hoặc yêu cầu chỉnh sửa."}</p>}
    </section>}
    {screen.id==="BUS-07" && <form className="dashboard-section" onSubmit={e=>{e.preventDefault();action(()=>json("/api/business/bookings",{...booking,slotId:Number(booking.slotId),packageId:Number(booking.packageId)}),"Đã ghi nhận yêu cầu đặt quảng cáo. Chờ quản lý chuẩn bị đề xuất hợp đồng.",()=>navigate("/business/contracts"));}}><h2>Yêu cầu đặt quảng cáo</h2>{data.company.application_status!=="APPROVED" && <p className="info-note">Hợp tác chưa được duyệt. <Link to="/business/partnership/status">Xem hồ sơ →</Link></p>}<div className="business-form-grid"><Field label="Tên yêu cầu"><input required maxLength={200} value={booking.name} onChange={e=>setBooking({...booking,name:e.target.value})}/></Field><Field label="Vị trí quảng cáo"><select required value={booking.slotId} onChange={e=>setBooking({...booking,slotId:e.target.value})}><option value="">Chọn vị trí</option>{catalog?.slots.map(slot=><option key={slot.id} value={slot.id}>{slot.name} · {slot.width} × {slot.height}</option>)}</select></Field><Field label="Gói quảng cáo"><select required value={booking.packageId} onChange={e=>setBooking({...booking,packageId:e.target.value})}><option value="">Chọn gói</option>{catalog?.offers.map(pack=><option key={pack.id} value={pack.id}>{pack.name} · {currency(pack.price)} · {pack.durationDays} ngày</option>)}</select></Field>{[["startDate","Ngày bắt đầu"],["endDate","Ngày kết thúc (bao gồm)"]].map(([key,label])=><Field key={key} label={label}><input type="date" required value={booking[key]} onChange={e=>setBooking({...booking,[key]:e.target.value})}/></Field>)}</div><p className="info-note">Giá dự kiến = giá gói + giá vị trí × số ngày / 30. Server tính lại và kiểm tra lịch. Gửi yêu cầu chưa giữ chỗ và chưa thanh toán.</p><div className="form-actions"><button disabled={busy || data.company.application_status!=="APPROVED" || catalog?.demo}>Gửi yêu cầu đặt quảng cáo</button><Link className="outline-button" to="/business/advertising/calendar">Xem lịch vị trí</Link></div></form>}
    {screen.id==="BUS-11" && <section className="dashboard-section"><div className="section-heading"><h2>Hợp đồng và yêu cầu đã gửi</h2><Link className="button-link" to="/business/bookings/new">Đặt quảng cáo mới</Link></div><div className="business-table-wrap"><table><thead><tr><th>Mã / tên</th><th>Vị trí</th><th>Khoảng chạy</th><th>Giá trị</th><th>Trạng thái</th><th/></tr></thead><tbody>{data.contracts.map(c=><tr key={c.contract_id}><td><strong>{c.contract_code}</strong><br/>{c.contract_name}</td><td>{c.slot_name_snapshot}</td><td>{time(c.start_at)}<br/>{time(c.end_at)} (kết thúc)</td><td>{currency(c.total_value)}</td><td><Badge value={c.status}/><br/>{status(c.payment_status)}</td><td><Link to={`/business/contracts/${c.contract_id}`}>Chi tiết →</Link></td></tr>)}</tbody></table></div>{!data.contracts.length && <p>Chưa có yêu cầu/hợp đồng. Hãy gửi yêu cầu đặt quảng cáo.</p>}</section>}
    {["BUS-08","BUS-09","BUS-10","BUS-12"].includes(screen.id) && <section className="dashboard-section"><h2>Thông tin hợp đồng</h2>{contract?<><Badge value={contract.status}/><dl className="business-details">{[["Mã hợp đồng",contract.contract_code],["Tên",contract.contract_name],["Vị trí",contract.slot_name_snapshot],["Gói",contract.package_name_snapshot],["Giá trị",currency(contract.total_value)],["Thanh toán",status(contract.payment_status)],["Bắt đầu",time(contract.start_at)],["Kết thúc",time(contract.end_at)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{contract.status==="ACTIVE" && contract.payment_status==="PAID"?<Link className="button-link" to="/business/campaigns/edit">Tạo chiến dịch →</Link>:<p className="info-note">Yêu cầu đã lưu thật. Quản lý chuẩn bị đề xuất, thương lượng và thanh toán chưa được nối API; chưa thể kích hoạt hợp đồng này. Không có hóa đơn giả.</p>}</>:<p>Chọn một hợp đồng từ <Link to="/business/contracts">danh sách hợp đồng</Link>.</p>}</section>}
    {screen.id==="BUS-13" && <section className="dashboard-section"><div className="section-heading"><h2>Chiến dịch của doanh nghiệp</h2><Link className="button-link" to="/business/campaigns/edit">Tạo chiến dịch</Link></div><div className="business-campaign-grid">{data.campaigns.map(c=><article key={c.campaign_id}>{c.media_url && <img src={c.media_url} alt={c.campaign_name}/>}<h3>{c.campaign_name}</h3><p>{c.contract_code}</p><Badge value={c.status}/><p>{time(c.scheduled_start_time)} → {time(c.scheduled_end_time)}</p><div className="record-actions"><Link to={`/business/campaigns/${c.campaign_id}`}>Chi tiết</Link>{editable(c.status) && <Link to={`/business/campaigns/edit/${c.campaign_id}`}>Chỉnh sửa</Link>}<Link to={`/business/performance/${c.campaign_id}`}>Báo cáo</Link></div></article>)}</div>{!data.campaigns.length && <p>Chưa có chiến dịch.</p>}</section>}
    {screen.id==="BUS-14" && <form className="dashboard-section" onSubmit={e=>{e.preventDefault();action(()=>json(`/api/business/campaigns${params.campaignId?`/${params.campaignId}`:""}`,{...campaignForm,contractId:Number(campaignForm.contractId)},params.campaignId?"PUT":"POST"),"Đã lưu chiến dịch nháp vào MySQL.",result=>navigate(`/business/campaigns/${result.id}/creative`));}}><h2>Thông tin chiến dịch</h2>{!activeContracts.length && <p className="info-note">Chưa có hợp đồng đã thanh toán còn hiệu lực. business.demo có sẵn hợp đồng mẫu để test.</p>}<div className="business-form-grid"><Field label="Hợp đồng đã thanh toán"><select required disabled={busy || Boolean(params.campaignId)} value={campaignForm.contractId} onChange={e=>{const ct=activeContracts.find(c=>String(c.contract_id)===e.target.value);setCampaignForm({...campaignForm,contractId:e.target.value,startTime:datetime(ct?.start_at),endTime:datetime(ct?.end_at)});}}><option value="">Chọn hợp đồng</option>{activeContracts.map(c=><option key={c.contract_id} value={c.contract_id}>{c.contract_code} · {c.slot_name_snapshot}</option>)}</select></Field><Field label="Tên chiến dịch"><input required maxLength={150} value={campaignForm.name} onChange={e=>setCampaignForm({...campaignForm,name:e.target.value})}/></Field>{[["startTime","Bắt đầu"],["endTime","Kết thúc"]].map(([key,label])=><Field key={key} label={label}><input required type="datetime-local" value={campaignForm[key]} onChange={e=>setCampaignForm({...campaignForm,[key]:e.target.value})}/></Field>)}<Field label="Mô tả"><textarea maxLength={2000} rows={4} value={campaignForm.description} onChange={e=>setCampaignForm({...campaignForm,description:e.target.value})}/></Field></div><button disabled={busy || !activeContracts.length || (params.campaignId && (!current || !editable(current.status)))}>Lưu nháp và tiếp tục</button></form>}
    {isCampaign && screen.id!=="BUS-14" && <section className="dashboard-section">{!current?<p>Không tìm thấy chiến dịch của doanh nghiệp này.</p>:<><h2>{current.campaign_name}</h2><Badge value={current.status}/><p>{current.contract_code} · {time(current.scheduled_start_time)} → {time(current.scheduled_end_time)}</p><p>{current.description}</p>{current.media_url && <img className="business-creative-preview" src={current.media_url} alt="Banner hiện tại"/>}<p>Banner: {status(current.creative_status)}</p>
      {screen.id==="BUS-15" && editable(current.status) && <form onSubmit={e=>{e.preventDefault();const body=new FormData();body.append("file",file);body.append("targetUrl",targetUrl);action(()=>apiRequest(`/api/business/campaigns/${current.campaign_id}/creative`,{method:"POST",body}),"Đã lưu phiên bản banner mới vào MySQL và kho tệp local.");}}><Field label={`Banner PNG/JPEG ${current.width_px} × ${current.height_px} px · tối đa 8 MB`}><input type="file" accept="image/png,image/jpeg" required disabled={busy} onChange={e=>setFile(e.target.files?.[0] || null)}/></Field><Field label="URL đích (http/https)"><input type="url" value={targetUrl} required maxLength={1000} onChange={e=>setTargetUrl(e.target.value)}/></Field><button disabled={busy || !file}>Tải và lưu banner</button><p className="info-note">Nhắm đối tượng theo chuyên mục, thẻ, địa lý và video chưa nối API; banner mới chưa tự được duyệt/phân phối.</p></form>}
      <div className="form-actions">{editable(current.status)?<><Link className="outline-button" to={`/business/campaigns/edit/${current.campaign_id}`}>Sửa thông tin</Link><Link className="outline-button" to={`/business/campaigns/${current.campaign_id}/creative`}>Banner</Link>{screen.id!=="BUS-16" && <Link className="button-link" to={`/business/campaigns/${current.campaign_id}/submit`}>Kiểm tra và gửi duyệt →</Link>}{screen.id==="BUS-16" && <button disabled={busy || current.creative_status!=="DRAFT"} onClick={()=>action(()=>apiRequest(`/api/business/campaigns/${current.campaign_id}/submit`,{method:"POST"}),"Đã gửi chiến dịch và đúng phiên bản banner để xét duyệt.",()=>navigate(`/business/campaigns/${current.campaign_id}`))}>Gửi chiến dịch và banner để duyệt</button>}</>:<p className="info-note">Bản đã gửi/đã duyệt bị khóa sửa. Việc xét duyệt, lên lịch và yêu cầu đổi quảng cáo sẽ được nối ở đợt tiếp theo.</p>}<Link className="outline-button" to="/business/campaigns">Danh sách chiến dịch</Link></div>
    </>}</section>}
    </>}
  </main>;
}
