import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../../store/AuthContext.jsx";
import { apiRequest } from "../../services/apiClient.js";

const number=value=>Number(value).toLocaleString("vi-VN");
const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function AnimatedValue({value,decimals=0,suffix=""}) {
  const [shown,setShown]=useState(value);
  useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setShown(value);return;} let frame;const from=performance.now(); const tick=now=>{const t=Math.min(1,(now-from)/650);setShown(value*(1-Math.pow(1-t,3)));if(t<1)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[value]);
  return <strong>{shown.toLocaleString("vi-VN",{maximumFractionDigits:decimals,minimumFractionDigits:decimals})}{suffix}</strong>;
}
export default function PerformancePage() {
  const {campaignId}=useParams();const {user}=useAuth();const business=user?.roles?.includes("BUSINESS");
  const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const [selected,setSelected]=useState(campaignId || "all");const [days,setDays]=useState("all");const [metric,setMetric]=useState("impressions");const [type,setType]=useState("line");const [hover,setHover]=useState(null);const [refresh,setRefresh]=useState(0);
  useEffect(()=>{setSelected(campaignId || "all");},[campaignId]);
  useEffect(()=>{let alive=true;setLoading(true);setError("");apiRequest("/api/advertising/performance").then(data=>{if(alive)setRows(data);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[refresh]);
  const campaigns=useMemo(()=>[...new Map(rows.map(row=>[String(row.campaignId),row.campaignName])).entries()],[rows]);
  const filtered=useMemo(()=>{const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(days)+1);return rows.filter(row=>(selected==="all"||String(row.campaignId)===selected)&&(days==="all"||String(row.metricDate).slice(0,10)>=iso(cutoff)));},[rows,selected,days]);
  const totals=filtered.reduce((acc,row)=>({impressions:acc.impressions+Number(row.impressions),clicks:acc.clicks+Number(row.clicks),invalidClicks:acc.invalidClicks+Number(row.invalidClicks)}),{impressions:0,clicks:0,invalidClicks:0});
  const daily=useMemo(()=>{const map=new Map();filtered.forEach(row=>{const date=String(row.metricDate).slice(0,10);const item=map.get(date)||{date,impressions:0,clicks:0};item.impressions+=Number(row.impressions);item.clicks+=Number(row.clicks);map.set(date,item);});return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date));},[filtered]);
  const shares=campaigns.map(([id,name])=>({id,name,total:filtered.filter(row=>String(row.campaignId)===id).reduce((sum,row)=>sum+Number(row.impressions),0)})).filter(item=>item.total>0);
  const max=Math.max(1,...daily.map(item=>item[metric]));const points=daily.map((item,i)=>[40+i*720/Math.max(1,daily.length-1),240-item[metric]/max*190]);
  const path=points.map(([x,y],i)=>`${i ? "L" : "M"}${x},${y}`).join(" ");
  const selectedPoint=hover===null ? daily.at(-1) : daily[hover];
  function exportCsv() {
    const safe=value=>`"${String(value).replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;
    const csv="\ufeff"+[["Ngày","Chiến dịch","Impressions","Clicks","Invalid clicks"],...filtered.map(row=>[String(row.metricDate).slice(0,10),row.campaignName,row.impressions,row.clicks,row.invalidClicks])].map(row=>row.map(safe).join(",")).join("\r\n");
    const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="the-pulse-performance.csv";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  return <main className="page-content performance-page"><div className="page-heading"><div><p className="eyebrow">CAMPAIGN ANALYTICS</p><h1>Hiệu quả quảng cáo</h1><p className="page-subtitle">Dữ liệu theo ngày từ MySQL · các chỉ số hiện là dữ liệu thử nghiệm, chưa ghi nhận lưu lượng thật.</p></div><button onClick={exportCsv} disabled={loading||!filtered.length}>↓ Xuất CSV</button></div>
    <div className="performance-filters"><label>Chiến dịch<select value={selected} onChange={e=>{setSelected(e.target.value);setHover(null);}} disabled={Boolean(campaignId)}><option value="all">Tất cả chiến dịch</option>{campaigns.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Thời gian<select value={days} onChange={e=>{setDays(e.target.value);setHover(null);}}><option value="all">Tất cả dữ liệu</option><option value="7">7 ngày gần đây</option><option value="30">30 ngày gần đây</option></select></label><button className="secondary-button" onClick={()=>setRefresh(value=>value+1)} disabled={loading}>↻ Làm mới</button><Link to={business ? "/business/campaigns" : "/ad-manager/campaign-monitor"}>Xem chiến dịch →</Link></div>
    {loading ? <div className="loading-card">Đang tải báo cáo…</div> : error ? <p role="alert" className="form-error">{error}</p> : <><div className="performance-kpis">{[["Lượt hiển thị",totals.impressions,0,"","◉"],["Lượt click",totals.clicks,0,"","↗"],["CTR",totals.impressions ? totals.clicks/totals.impressions*100 : 0,2,"%","◎"],["Click không hợp lệ",totals.invalidClicks,0,"","◇"]].map(([label,value,decimals,suffix,icon])=><article key={label}><span className="kpi-icon">{icon}</span><span>{label}</span><AnimatedValue value={value} decimals={decimals} suffix={suffix}/><small>Tổng trong khoảng đã chọn</small></article>)}</div>
    {!filtered.length ? <p className="info-note">Không có dữ liệu cho chiến dịch hoặc khoảng thời gian này.</p> : <><div className="performance-charts"><section className="dashboard-section"><div className="performance-chart-heading"><div><h2>Nhịp phân phối</h2><p>Di chuột hoặc chọn ngày để xem số liệu.</p></div><div className="chart-switches"><button aria-pressed={metric==="impressions"} onClick={()=>setMetric("impressions")}>Hiển thị</button><button aria-pressed={metric==="clicks"} onClick={()=>setMetric("clicks")}>Clicks</button><button aria-pressed={type==="line"} onClick={()=>setType(value=>value==="line" ? "bar" : "line")}>{type==="line" ? "Biểu đồ cột" : "Biểu đồ đường"}</button></div></div>
      <div className="chart-insight" role="status">{selectedPoint?.date} <strong>{number(selectedPoint?.[metric]||0)}</strong> {metric==="impressions" ? "lượt hiển thị" : "clicks"}</div>
      <svg className="performance-svg" viewBox="0 0 800 280" role="img" aria-label={`Biểu đồ ${metric} theo ngày; bảng số liệu ở bên dưới`} key={`${metric}-${type}-${selected}-${days}`}><defs><linearGradient id="performance-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#cc1836" stopOpacity=".22"/><stop offset="1" stopColor="#cc1836" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(i=><g key={i}><line x1="40" x2="770" y1={50+i*47.5} y2={50+i*47.5} stroke="#d8dee6" strokeDasharray="4 5"/><text x="0" y={54+i*47.5} fontSize="9" fill="#7c8796">{number(Math.round(max*(1-i/4)))}</text></g>)}
        {type==="line" ? <><path d={`${path} L${points.at(-1)?.[0]},240 L40,240 Z`} fill="url(#performance-fill)"/><path className="chart-line" d={path} fill="none" stroke="#cc1836" strokeWidth="3" pathLength="1"/>{points.map(([x,y],i)=><circle key={i} cx={x} cy={y} r={hover===i ? 7 : 4} fill="#cc1836" stroke="white" strokeWidth="2"/>)}</> : points.map(([x,y],i)=><rect className="chart-bar" key={i} x={x-8} y={y} width="16" height={Math.max(0,240-y)} rx="4" fill={hover===i ? "#862441" : "#cc1836"}/>)}
        {points.map(([x],i)=><rect key={i} x={x-720/Math.max(1,daily.length)/2} y="30" width={720/Math.max(1,daily.length)} height="220" fill="transparent" onMouseEnter={()=>setHover(i)}/>)}</svg>
      <div className="chart-days">{daily.map((item,i)=><button key={item.date} className={hover===i ? "selected" : ""} onFocus={()=>setHover(i)} onClick={()=>setHover(i)}>{item.date.slice(5)}</button>)}</div></section>
      <aside className="dashboard-section campaign-share"><h2>Phân bổ lượt hiển thị</h2><div className="share-ring" style={{background:`conic-gradient(${shares.map((item,i)=>{const from=shares.slice(0,i).reduce((sum,x)=>sum+x.total,0)/totals.impressions*100;return `${["#cc1836","#2b8790","#e0ab4f","#8073c4"][i%4]} ${from}% ${from+item.total/totals.impressions*100}%`;}).join(",")})`}}><div><AnimatedValue value={shares.length}/><small>chiến dịch</small></div></div>{shares.map((item,i)=><button key={item.id} className="share-item" onClick={()=>{setSelected(item.id);setHover(null);}}><i style={{background:["#cc1836","#2b8790","#e0ab4f","#8073c4"][i%4]}}/><span>{item.name}</span><strong>{(item.total/totals.impressions*100).toFixed(1)}%</strong></button>)}</aside></div>
      <section className="dashboard-section performance-details"><h2>Số liệu theo ngày</h2><div className="data-table"><table><thead><tr><th>Ngày</th><th>Chiến dịch</th><th>Hiển thị</th><th>Clicks</th><th>CTR</th><th>Click không hợp lệ</th></tr></thead><tbody>{filtered.map(row=><tr key={`${row.campaignId}-${row.metricDate}`}><td>{String(row.metricDate).slice(0,10)}</td><td>{row.campaignName}</td><td>{number(row.impressions)}</td><td>{number(row.clicks)}</td><td>{row.impressions ? (row.clicks/row.impressions*100).toFixed(2) : "0"}%</td><td>{number(row.invalidClicks)}</td></tr>)}</tbody></table></div></section></>}</>}
  </main>;
}
