export const screens = [
  { id: "PUB-01", name: "Home and News Feed", feature: "Public News", path: "/", area: "public", bf: ["BF-02", "BF-08"], uc: ["UC-02", "UC-03", "UC-04", "UC-31"] },
  { id: "PUB-02", name: "Search Results", feature: "Public News", path: "/search", area: "public", uc: ["UC-01", "UC-03", "UC-04"] },
  { id: "PUB-03", name: "Article Detail", feature: "Public News", path: "/articles/:slug", area: "public", bf: ["BF-02", "BF-08"], uc: ["UC-02", "UC-15", "UC-16", "UC-31"] },
  { id: "PUB-04", name: "Premium Paywall", feature: "Public News", path: "/premium/paywall", area: "public", bf: ["BF-02"], uc: ["UC-15"] },
  { id: "AUTH-01", name: "Login", feature: "Authentication", path: "/login", area: "auth", uc: ["UC-06"] },
  { id: "AUTH-02", name: "Account Registration", feature: "Authentication", path: "/register", area: "auth", uc: ["UC-05"] },
  { id: "AUTH-03", name: "Forgot Password", feature: "Authentication", path: "/forgot-password", area: "auth", uc: ["UC-07"] },
  { id: "AUTH-04", name: "Set New Password", feature: "Authentication", path: "/reset-password", area: "auth", uc: ["UC-07"] },
  { id: "ACC-01", name: "Profile and Security", feature: "Account", path: "/account/profile", area: "account", roles: ["READER", "SUBSCRIBER", "BUSINESS", "AD_MANAGER", "ADMINISTRATOR"], uc: ["UC-08"] },
  { id: "ACC-02", name: "Notification Center", feature: "Account", path: "/account/notifications", area: "account", roles: ["READER", "SUBSCRIBER", "BUSINESS", "AD_MANAGER", "ADMINISTRATOR"] },
  { id: "ACC-03", name: "Bookmarked Articles", feature: "Account", path: "/account/bookmarks", area: "account", roles: ["READER", "SUBSCRIBER"], bf: ["BF-02"], uc: ["UC-10"] },
  { id: "PRE-01", name: "Subscription Packages", feature: "Premium Subscription", path: "/premium/packages", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01"], uc: ["UC-11"] },
  { id: "PRE-02", name: "Package Detail", feature: "Premium Subscription", path: "/premium/packages/:packageId", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01"], uc: ["UC-11"] },
  { id: "PRE-03", name: "Premium Checkout", feature: "Premium Subscription", path: "/premium/checkout/:packageId", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01"], uc: ["UC-12", "UC-13"] },
  { id: "PRE-04", name: "Premium Payment Result", feature: "Premium Subscription", path: "/premium/payment-result", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01"], uc: ["UC-12", "UC-13"] },
  { id: "PRE-05", name: "My Subscription", feature: "Premium Subscription", path: "/premium/my-subscription", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01", "BF-02"], uc: ["UC-14"] },
  { id: "PRE-06", name: "Premium Transaction History", feature: "Premium Subscription", path: "/premium/transactions", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01"], uc: ["UC-14"] },
  { id: "PRE-07", name: "Premium Receipt Detail", feature: "Premium Subscription", path: "/premium/transactions/:transactionId", area: "premium", roles: ["READER", "SUBSCRIBER"], bf: ["BF-01"], uc: ["UC-14"] },
  { id: "BUS-01", name: "Business Dashboard", feature: "Business Partnership", path: "/business", area: "business", roles: ["BUSINESS"], bf: ["BF-03", "BF-05", "BF-06", "BF-08"] },
  { id: "BUS-02", name: "Company Profile", feature: "Business Partnership", path: "/business/company", area: "business", roles: ["BUSINESS"], bf: ["BF-03"], uc: ["UC-38"] },
  { id: "BUS-03", name: "Partnership Application", feature: "Business Partnership", path: "/business/partnership/apply", area: "business", roles: ["BUSINESS"], bf: ["BF-03"], uc: ["UC-17", "UC-18"] },
  { id: "BUS-04", name: "Partnership Application Status", feature: "Business Partnership", path: "/business/partnership/status", area: "business", roles: ["BUSINESS"], bf: ["BF-03", "BF-04"], uc: ["UC-18", "UC-20"] },
  { id: "BUS-05", name: "Advertising Price List", feature: "Booking and Contract", path: "/business/advertising/prices", area: "business", roles: ["BUSINESS"], bf: ["BF-05"], uc: ["UC-21"] },
  { id: "BUS-06", name: "Slot Availability Calendar", feature: "Booking and Contract", path: "/business/advertising/calendar", area: "business", roles: ["BUSINESS"], bf: ["BF-05"], uc: ["UC-21"] },
  { id: "BUS-07", name: "Booking Request", feature: "Booking and Contract", path: "/business/bookings/new", area: "business", roles: ["BUSINESS"], bf: ["BF-05"], uc: ["UC-22"] },
  { id: "BUS-08", name: "Booking and Contract Proposal", feature: "Booking and Contract", path: "/business/bookings/:contractId/proposal", area: "business", roles: ["BUSINESS"], bf: ["BF-05"], uc: ["UC-23", "UC-24"] },
  { id: "BUS-09", name: "Advertising Checkout", feature: "Booking and Contract", path: "/business/contracts/:contractId/checkout", area: "business", roles: ["BUSINESS"], bf: ["BF-05"], uc: ["UC-24"] },
  { id: "BUS-10", name: "Advertising Payment Result", feature: "Booking and Contract", path: "/business/contracts/payment-result", area: "business", roles: ["BUSINESS"], bf: ["BF-05"], uc: ["UC-24"] },
  { id: "BUS-11", name: "Contract List", feature: "Booking and Contract", path: "/business/contracts", area: "business", roles: ["BUSINESS"], bf: ["BF-05", "BF-06"] },
  { id: "BUS-12", name: "Contract Detail and Invoice", feature: "Booking and Contract", path: "/business/contracts/:contractId", area: "business", roles: ["BUSINESS"], bf: ["BF-05", "BF-06"], uc: ["UC-24"] },
  { id: "BUS-13", name: "Campaign List", feature: "Campaign", path: "/business/campaigns", area: "business", roles: ["BUSINESS"], bf: ["BF-06", "BF-07", "BF-08"], uc: ["UC-25"] },
  { id: "BUS-14", name: "Campaign Create and Edit", feature: "Campaign", path: "/business/campaigns/edit/:campaignId?", area: "business", roles: ["BUSINESS"], bf: ["BF-06"], uc: ["UC-25"] },
  { id: "BUS-15", name: "Creative and Targeting", feature: "Campaign", path: "/business/campaigns/:campaignId/creative", area: "business", roles: ["BUSINESS"], bf: ["BF-06"], uc: ["UC-26"] },
  { id: "BUS-16", name: "Campaign Submission Review", feature: "Campaign", path: "/business/campaigns/:campaignId/submit", area: "business", roles: ["BUSINESS"], bf: ["BF-06"], uc: ["UC-27"] },
  { id: "BUS-17", name: "Campaign Status and Detail", feature: "Campaign", path: "/business/campaigns/:campaignId", area: "business", roles: ["BUSINESS"], bf: ["BF-06", "BF-07"], uc: ["UC-27", "UC-39"] },
  { id: "BUS-18", name: "Campaign Performance Overview", feature: "Campaign Performance", path: "/business/performance", area: "business", roles: ["BUSINESS"], bf: ["BF-08"], uc: ["UC-32"] },
  { id: "BUS-19", name: "Campaign Metrics and Final Report", feature: "Campaign Performance", path: "/business/performance/:campaignId", area: "business", roles: ["BUSINESS"], bf: ["BF-08"], uc: ["UC-32"] },
  { id: "ADM-01", name: "Ad Manager Dashboard", feature: "Ad Manager", path: "/ad-manager", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-04", "BF-05", "BF-07", "BF-08"] },
  { id: "ADM-02", name: "Partnership Review Queue", feature: "Partnership Review", path: "/ad-manager/partnerships", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-04"], uc: ["UC-19"] },
  { id: "ADM-03", name: "Partnership Review Detail", feature: "Partnership Review", path: "/ad-manager/partnerships/:companyId", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-04"], uc: ["UC-19", "UC-20"] },
  { id: "ADM-04", name: "Booking Review Queue", feature: "Contract Review", path: "/ad-manager/bookings", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-05"], uc: ["UC-23"] },
  { id: "ADM-05", name: "Booking Availability and Proposal", feature: "Contract Review", path: "/ad-manager/bookings/:contractId/proposal", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-05"], uc: ["UC-23"] },
  { id: "ADM-06", name: "Contract Revision and Payment Status", feature: "Contract Review", path: "/ad-manager/contracts/:contractId", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-05"], uc: ["UC-23", "UC-24"] },
  { id: "ADM-07", name: "Campaign Review Queue", feature: "Campaign Review", path: "/ad-manager/campaigns", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-07"], uc: ["UC-28", "UC-29"] },
  { id: "ADM-08", name: "Campaign and Creative Review", feature: "Campaign Review", path: "/ad-manager/campaigns/:campaignId/review", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-07"], uc: ["UC-28", "UC-29", "UC-30"] },
  { id: "ADM-09", name: "Active Campaign Monitor", feature: "Campaign Operations", path: "/ad-manager/campaign-monitor", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-08"], uc: ["UC-30", "UC-39"] },
  { id: "ADM-10", name: "Advertising Performance Report", feature: "Campaign Performance", path: "/ad-manager/reports", area: "adManager", roles: ["AD_MANAGER"], bf: ["BF-08"], uc: ["UC-32"] },
  { id: "CFG-01", name: "Administration Dashboard", feature: "Administration", path: "/admin", area: "admin", roles: ["ADMINISTRATOR"] },
  { id: "CFG-02", name: "User and Role Management", feature: "Administration", path: "/admin/users", area: "admin", roles: ["ADMINISTRATOR"], uc: ["UC-34"] },
  { id: "CFG-03", name: "Subscription Package Management", feature: "Administration", path: "/admin/subscription-packages", area: "admin", roles: ["ADMINISTRATOR"], bf: ["BF-01"], uc: ["UC-35"] },
  { id: "CFG-04", name: "Advertising Slot Management", feature: "Administration", path: "/admin/ad-slots", area: "admin", roles: ["ADMINISTRATOR", "AD_MANAGER"], bf: ["BF-05", "BF-08"], uc: ["UC-33"] },
  { id: "CFG-05", name: "B2B Package and Pricing Management", feature: "Administration", path: "/admin/b2b-packages", area: "admin", roles: ["ADMINISTRATOR", "AD_MANAGER"], bf: ["BF-05"], uc: ["UC-36"] },
  { id: "CFG-06", name: "System Settings", feature: "Administration", path: "/admin/settings", area: "admin", roles: ["ADMINISTRATOR"], uc: ["UC-37"] },
];

export const screenById = Object.fromEntries(screens.map((screen) => [screen.id, screen]));
