spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
